Pipeline - draft1
sanger-tol/longreadmag pull request #1
Opened 2024-11-26 15:50 UTC by prototaxites

Adds:
- [x] Input from YAML
- [x] Assembly
    - [x] metaMDBG 
    - [x] assembly statistics/num circular
- [x] Read mapping to assembly - hi-c and pacbio
- Binning with
    - [x] metabat2
    - [x] maxbin2
    - [x] bin3c
    - [x] metator
 - Bin refinement
     - [x] gene prediction with pyrodigal 
     - [x] magscot
     - [x] dastool
- Bin QC
    - [x] Checkm
    - [x] Seqkit statistics
    - [x] infernal + trnascan-se - count trnas
- Taxonomy
    - [x] GTDBTk
    - [x] TaxKit - get NCBI taxids
- Summary
    - [x] assembly statistics
    - [x] bin statistics and scoring

2024-12-12 11:11 UTC, sanger-tolsoft commented
<!-- add-pr-comment:add-pr-comment -->

> [!WARNING]
> Newer version of the nf-core template is available.
>
> Your pipeline is using an old version of the nf-core template: 3.0.2.
> Please update your pipeline to the latest version.
>
> For more documentation on how to update your pipeline, please see the [nf-core documentation](https://github.com/nf-core/tools?tab=readme-ov-file#sync-a-pipeline-with-the-template) and [Synchronisation documentation](https://nf-co.re/docs/contributing/sync).

2025-01-15 14:37 UTC, weaglesBio commented on subworkflows/local/assembly.nf
Is ch_proteins required?

2025-01-17 11:21 UTC, weaglesBio commented on modules/local/bin_rrnas/environment.yml
Are these dependencies required for this module?

2025-01-17 13:38 UTC, prototaxites commented on modules/local/bin_rrnas/environment.yml
Oops, forgot to change that one!

2025-01-17 13:56 UTC, weaglesBio commented on lib/TreeValProject.groovy
Is this needed or should it be renamed to reflect the project?

2025-01-17 13:56 UTC, weaglesBio commented on lib/WorkflowTreeVal.groovy
Is this needed or should it be renamed to reflect the project?

2025-01-17 13:57 UTC, weaglesBio commented on modules/local/bin3c/cluster/main.nf
Could you add process label?

2025-01-17 14:00 UTC, weaglesBio commented on modules/local/magscot/magscot/main.nf
Should this handle being unavailable in conda?

2025-01-17 14:19 UTC, prototaxites commented on lib/TreeValProject.groovy
I just kept it as a holdover from when you started the repo - I don't think I need anything in it but wasn't sure if it was required for anything Sanger-specific

2025-01-17 14:20 UTC, prototaxites commented on modules/local/magscot/magscot/main.nf
Yes

2025-01-17 15:40 UTC, weaglesBio commented on README.md
Multiqc is still linked from metaMDBG

2025-01-17 15:45 UTC, weaglesBio requested changes
Looking good, just need to resolve a few comments.

2025-02-28 15:11 UTC, DLBPointon approved these changes
Hi Jim,
Great work, the only things I have to suggest are to add more comments. Like in a couple of the pipelines we have:
```
    //
    // MODULE: generate a cram csv file containing the required parametres for CRAM_FILTER_ALIGN_BWAMEM2_FIXMATE_SORT
    //
    GENERATE_CRAM_CSV (
        hic_reads_path
    )
    ch_versions         = ch_versions.mix( GENERATE_CRAM_CSV.out.versions )


    //
    // SUBWORKFLOW: mapping hic reads using minimap2
    //
    HIC_MINIMAP2 (
        reference_tuple.filter{ meta, _fasta -> meta.aligner == 'minimap2' },
        GENERATE_CRAM_CSV.out.csv,
        SAMTOOLS_FAIDX.out.fai
    )
```

Granted this has kind of fallen out of favour, so I won't make it a *need*, but I think it is useful.

Also, I take it NF-Test isn't ready seeing as there is no snap?

2025-02-28 15:28 UTC, prototaxites commented
Many thanks Damon! Yes, comments were somewhere on my list of tasks and slightly slipped past me - I will go through and add some now.

No luck yet with nf-test but it would nice to be able to get it working. I have created an option to provide a pre-built assembly, so hopefully that will help with improving the stability of the test outputs.

2025-02-28 16:06 UTC, weaglesBio approved these changes

2025-02-28 18:02 UTC, merged